//creating class with use of variable
class CreatingVariable
{
	public static void main(String[] args) 
	{
		int num; // integer typed number

		num = 100; //assigned value to num variable

		System.out.println("This is num: " + num); //print value of variable num

		num = num * 2; //num multiplied by 2

		System.out.print("The value of num * 2: ");//print value of variable num
		System.out.println(num); 

	}
}